/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppLayoutRouteImport } from './routes/_app/layout'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSuperRouteImport } from './routes/_app/super'
import { Route as AppEventIndexRouteImport } from './routes/_app/event/index'
import { Route as AppEventEventIdRouteImport } from './routes/_app/event/$eventId'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppSuperRoute = AppSuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppEventIndexRoute = AppEventIndexRouteImport.update({
  id: '/event/',
  path: '/event/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppEventEventIdRoute = AppEventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/super': typeof AppSuperRoute
  '/': typeof AppIndexRoute
  '/event/$eventId': typeof AppEventEventIdRoute
  '/event': typeof AppEventIndexRoute
}
export interface FileRoutesByTo {
  '/super': typeof AppSuperRoute
  '/': typeof AppIndexRoute
  '/event/$eventId': typeof AppEventEventIdRoute
  '/event': typeof AppEventIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_app/super': typeof AppSuperRoute
  '/_app/': typeof AppIndexRoute
  '/_app/event/$eventId': typeof AppEventEventIdRoute
  '/_app/event/': typeof AppEventIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/super' | '/' | '/event/$eventId' | '/event'
  fileRoutesByTo: FileRoutesByTo
  to: '/super' | '/' | '/event/$eventId' | '/event'
  id:
    | '__root__'
    | '/_app'
    | '/_app/super'
    | '/_app/'
    | '/_app/event/$eventId'
    | '/_app/event/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/super': {
      id: '/_app/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof AppSuperRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/event/': {
      id: '/_app/event/'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof AppEventIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/event/$eventId': {
      id: '/_app/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof AppEventEventIdRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppSuperRoute: typeof AppSuperRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEventEventIdRoute: typeof AppEventEventIdRoute
  AppEventIndexRoute: typeof AppEventIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppSuperRoute: AppSuperRoute,
  AppIndexRoute: AppIndexRoute,
  AppEventEventIdRoute: AppEventEventIdRoute,
  AppEventIndexRoute: AppEventIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
